### ISSUE TITLE
请教一下，loss用的什么呢，还有一些训练的trick可以讲一下吗

### ISSUE THREAD

**Issue by interstellar-ai** [alimama-creative/FLUX-Controlnet-Inpainting#1]
RT

**Comment by JPlin** [comment]
We used FlowMatching loss and trained similarly to the original SD ControlNet, utilizing a dataset on the scale of tens of millions.

**Comment by ArlenCHEN** [comment]
hi @JPlin 

Just wonder if the training pipeline is similar to this one??:
<img width="630" alt="截屏2024-10-09 10 46 51" src="https://github.com/user-attachments/assets/0045f51e-abcd-4103-a3f8-a108ebebccff">

Appreciate it!!!
