### ISSUE TITLE
ControlNetInpaintingAliMamaApply

### ISSUE THREAD

**Issue by shanghaiyangming** [alimama-creative/FLUX-Controlnet-Inpainting#13]
comfyUI中找不到ControlNetInpaintingAliMamaApply 如何安装？？？

**Comment by shanghaiyangming** [comment]
什么意思？问题没解决啊？

**Comment by shanghaiyangming** [comment]
![image](https://github.com/user-attachments/assets/e76f00e6-40f6-4248-837f-8269b4955e18)

**Comment by shanghaiyangming** [comment]
![image](https://github.com/user-attachments/assets/6f3f04cf-8083-4aa0-8b14-34abac908af2)

**Comment by shanghaiyangming** [comment]
麻烦提供下插件的下载地址，谢谢~~

**Comment by JPlin** [comment]
comfyui 更新到官方最新版本即可
