### ISSUE TITLE
custom nodes not found

### ISSUE THREAD

**Issue by chenxianpao** [alimama-creative/FLUX-Controlnet-Inpainting#18]
When loading the graph, the following node types were not found:
CLIPTextEncodeFlux
ControlNetInpaintingAliMamaApply
加载失败的节点会显示为红色

已经是最新的comfyui了。

**Comment by JPlin** [comment]
能发下comfyui的版本吗

**Comment by chenxianpao** [comment]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/fb379516-3f1e-4066-91af-111d4ee21643">

**Comment by chenxianpao** [comment]
应该是我的comfyui缺文件了。
