### ISSUE TITLE
comfyui workflow

### ISSUE THREAD

**Issue by zhaoqi571436204** [alimama-creative/FLUX-Controlnet-Inpainting#2]
If so, please release the specific workflow

**Comment by JPlin** [comment]
We are trying to adapt ComfyUI. Once it's complete, the information will be updated in the README. Please stay tuned.

**Comment by StartHua** [comment]
> We are trying to adapt ComfyUI. Once it's complete, the information will be updated in the README. Please stay tuned.

啥时候出啊，最好是能有量化的4090都能跑

**Comment by JPlin** [comment]
预计一周内，量化的我们会尝试下

**Comment by JPlin** [comment]
ComfyUI now supports inference for Alimama inpainting ControlNet. Workflow can be downloaded from [here](https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Alpha/resolve/main/images/alimama-flux-controlnet-inpaint.json). See [Readme](https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Alpha) for more information.
