### ISSUE TITLE
beta model infer error:  python main.py

### ISSUE THREAD

**Issue by greasebig** [alimama-creative/FLUX-Controlnet-Inpainting#33]
diffusers==0.30.2 and transformers==4.42.0

es/diffusers/models/attention_processor.py", line 1778, in __call__
    query = apply_rotary_emb(query, image_rotary_emb)

es/diffusers/models/embeddings.py", line 718, in apply_rotary_emb
    cos, sin = freqs_cis  # [S, D]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by greasebig** [comment]
592         if use_real:                                                                                    
 593  ->         cos, sin = freqs_cis  # [S, D]

**Comment by davidz123** [comment]
@greasebig Meeting the same problem. Has the problem been solved?

**Comment by nitec427** [comment]
Hİ @Xuan-World, could you share the required changes for the issue. Best!
