### ISSUE TITLE
找不到 __init__.py 文件

### ISSUE THREAD

**Issue by Tanglinling** [alimama-creative/FLUX-Controlnet-Inpainting#8]
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: E:\AIGC\ComfyUI_windows_portable\ComfyUI\web
E:\AIGC\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: torch.cuda.amp.custom_fwd(args...) is deprecated. Please use torch.amp.custom_fwd(args..., device_type='cuda') instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AIGC\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\FLUX-Controlnet-Inpainting\\__init__.py'

Cannot import E:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\FLUX-Controlnet-Inpainting module for custom nodes: [Errno 2] No such file or directory: 'E:\\AIGC\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\FLUX-Controlnet-Inpainting\\__init__.py'

Import times for custom nodes:
   0.0 seconds: E:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): E:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\FLUX-Controlnet-Inpainting

**Comment by JPlin** [comment]
该github repo是基于Diffusers的推理脚本，不是ComfyUI的custom_node。官方ComfyUI 已经集成了[相关节点](https://github.com/comfyanonymous/ComfyUI/commit/f48e390032f8d27a450a35ef4aa4b775b078cbf9)。需要从huggingface上下载[权重](https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Alpha)到comfyui目录里使用。
